# Generated by Django 4.1.6 on 2023-02-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Holmes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
