# Generated by Django 4.1.6 on 2023-02-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Holmes", "0005_alter_user_contact_alter_user_highest_qualification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="title",
            field=models.CharField(max_length=40),
        ),
    ]
