# Generated by Django 4.1.6 on 2023-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Holmes", "0006_alter_jobs_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degree",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
