# Generated by Django 4.1.6 on 2023-02-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Holmes", "0007_alter_degree_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="highest_qualification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Holmes.degree",
            ),
        ),
    ]
