# Generated by Django 4.1.6 on 2023-02-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Holmes", "0008_alter_user_highest_qualification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dp",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
