# Generated by Django 4.1.6 on 2023-02-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Holmes", "0009_user_dp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
    ]
