# Generated by Django 4.1.6 on 2023-02-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Holmes", "0012_alter_skill_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobs",
            name="skills",
        ),
        migrations.AddField(
            model_name="jobs",
            name="skills",
            field=models.ManyToManyField(to="Holmes.skill"),
        ),
    ]
