# Generated by Django 4.1.6 on 2023-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Holmes", "0015_alter_user_dp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dp",
            field=models.ImageField(
                blank=True, default="th_19.jfif", null=True, upload_to="media"
            ),
        ),
    ]
