# Generated by Django 4.1.6 on 2023-02-10 19:43

import Holmes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Holmes", "0020_alter_user_dp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dp",
            field=models.ImageField(
                default=Holmes.models.default_image_path, upload_to="media"
            ),
        ),
    ]
