# Generated by Django 4.1.6 on 2023-02-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Holmes", "0021_alter_user_dp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="media"),
        ),
    ]
