# Generated by Django 4.1.6 on 2023-02-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Holmes", "0022_user_resume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobs",
            name="required_qualifications",
        ),
        migrations.AddField(
            model_name="jobs",
            name="required_qualifications",
            field=models.ManyToManyField(to="Holmes.degree"),
        ),
    ]
